---
title: "標題"
subtitle: "副標題"
author: | 
  | 第 x 組
  | 組員1, 組員2, 組員3, 組員4
date: "2019-01-11"
toc-title: "目錄"
paperwidth: 8.27in
paperheight: 11.69in
output:
  pagedown::html_paged:
    toc: true
    front_cover: "styles/cover.jpg"
    back_cover: "styles/cover.jpg"
    # change to true for a self-contained document, but it'll be a litte slower for Pandoc to render
    self_contained: false
    css: ["styles/pagedown.css", "default-fonts", "default-page", "default"]
  html_document:
    number_sections: yes
    highlight: tango
    toc: no
    css: "styles/html_document.css"
#knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r}
# 執行資料分析
source("R/analysis.R")
```

如何將此 Rmd 輸出成 PDF?  
依序執行下方指令：

```r
rmarkdown::render("index.Rmd")
pagedown::chrome_print("index.html")
```


簡介
=====================

請簡要說明你們的專案


方法
=====================

請在這裡寫下方法。請在這裡寫下方法。請在這裡寫下方法。請在這裡寫下方法。請在這裡寫下方法。

## 資料取得

## 原始碼運作說明


結果
=====================

請在這裡寫下結果。請在這裡寫下結果。請在這裡寫下結果。請在這裡寫下結果。請在這裡寫下結果。請在這裡寫下結果。

```{r, fig.cap='iris 的散布圖'}
# 關於變數 pl, 見 R/analysis.R
pl
```



討論與貢獻
=====================

請在這裡寫下討論。請在這裡寫下討論。請在這裡寫下討論。請在這裡寫下討論。

